### ISSUE TITLE
Commands with Flags and CollectedParameters don't work as expected

### ISSUE THREAD

**Issue by jmmaloney4** [jakeheis/SwiftCLI#78]
I have a command like this:

```swift
class HelloCommand: Command {
    let name = "hello"
    let json = Flag("-j", "--json")
    let files = CollectedParameter()

    func execute() throws {
        print("\(files.value)")
    }
}
```

However, whenever I pass the `--json` argument it is just grouped into `files`, regardless of where it is placed. Maybe this is a known limitation or maybe I am using it wrong, but it feels like a parser error. If I replace `files` with a regular `Parameter` it works just fine.

The rest of the framework is great though, very intuitive and easy to use. Thanks for your work on this.

**Comment by jakeheis** [comment]
Thanks for the issue report! This behavior was intentional to allow use cases like:

`swift run git commit -a`. 

If you we're building `swift` with `SwiftCLI`, you'd probably have a command that looked like:

```swift
class RunCommand {
    let name = "run"
    let executable = OptionalParameter()
    let arguments = OptionalCollectedParameter()
}
```

The command shouldn't fail because "-a" is an unrecognized flag, it should instead be grouped in `arguments.value`.

Starting in `5.3.0`, however, you can now control this parsing behavior. If you want to continue recognizing options amidst collected parameter values, you can say:

```swift
cli.parser.parseOptionsAfterCollectedParameter = true
```

Hopefully that should fix your issue! Feel free to reopen if it doesn't
