### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by M-Tallal-Habib** [jakeheis/SwiftCLI#95]
![Screenshot from 2020-03-04 17-21-28](https://user-images.githubusercontent.com/40626630/75879131-a5be9200-5e3c-11ea-85c7-eda953d97e2f.png)

**Comment by marcelmendesfilho** [comment]
I'm facing exactly same issue. Has anyone solved this?

**Comment by jakeheis** [comment]
This usually means that another package depended on by your package depends on a different version of SwiftCLI. It usually can be fixed by changing which version of SwiftCLI you use or by changing the version of the other dependency you use. If you need help debugging, it would help to see your `Package.swift`

**Comment by jakeheis** [comment]
Closing for now -- feel free to reopen if changing dependency versions didn't work!
